# -*- coding: utf-8 -*-
"""
/***************************************************************************
 UrbanMatrix
                                 A QGIS plugin
 A plugin to automate and apply Matrix Method for urban applications
 Template generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-04-08
        copyright            : (C) 2025 by Cristhian Sanchez
        email                : crivisan1994@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load UrbanMatrix class from file UrbanMatrix.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .UrbanMatrix import UrbanMatrix
    return UrbanMatrix(iface)
